USE master;
GO

IF EXISTS (SELECT 1 FROM SYS.databases WHERE name = 'PetcareX')
    DROP DATABASE PetcareX;
go

CREATE DATABASE PetcareX;
GO
USE PetcareX;
GO

--- KHACH HANG VA THU CUNG

--- KHAM BENH VA TIEM PHONG

--- KINH DOANH

--- CHI NHANH VA NHAN SU

CREATE TABLE LOAIDICHVU (
    MALOAIDV   CHAR(5) PRIMARY KEY,
    TENDV      NVARCHAR(100) NOT NULL,
    MOTA       NVARCHAR(255)
);

CREATE TABLE CHINHANH (
    MACN       CHAR(5) PRIMARY KEY,
    TENCN      NVARCHAR(50) NOT NULL,
    DIACHI     NVARCHAR(200) NOT NULL,
    SDT        CHAR(10) UNIQUE,                   
    GIODM      TIME NOT NULL,
    GIODONGCUA TIME NOT NULL,
    CHECK (SDT NOT LIKE '%[^0-9]%')               
);

CREATE TABLE CUNGCAP (
    MALOAIDV CHAR(5) NOT NULL,
    MACN     CHAR(5) NOT NULL,
    PRIMARY KEY (MALOAIDV, MACN)
);

CREATE TABLE NHANVIEN (
    MANV         CHAR(5) PRIMARY KEY,
    HOTEN        NVARCHAR(100) NOT NULL,
    NGAYSINH     DATE NOT NULL,
    GIOITINH     NVARCHAR(5) CHECK (GIOITINH IN (N'Nam', N'Nữ', N'Khác')),
    SODIENTHOAI  CHAR(10) UNIQUE,
    LUONGCOBAN   DECIMAL(12,2) CHECK (LUONGCOBAN >= 0),
    CHECK (SODIENTHOAI NOT LIKE '%[^0-9]%')
);

CREATE TABLE LAMVIEC (
    MACN        CHAR(5) NOT NULL,
    MANV        CHAR(5) NOT NULL,
    NGAYBATDAU  DATE NOT NULL,
    NGAYKETTHUC DATE,
    PRIMARY KEY (MACN, MANV, NGAYBATDAU),
    CHECK (NGAYKETTHUC IS NULL OR NGAYKETTHUC >= NGAYBATDAU)
);


CREATE TABLE QUANLY (
    MANV         CHAR(5) NOT NULL,
    NGAYBONHIEM  DATE NOT NULL,
    MACN         CHAR(5) NOT NULL,
    PRIMARY KEY (MANV, MACN)
);

CREATE TABLE BACSI (
    MANV         CHAR(5) PRIMARY KEY,
    BANGCAP      NVARCHAR(100) NOT NULL,
    KINHNGHIEM   INT CHECK (KINHNGHIEM >= 0)
);

ALTER TABLE CUNGCAP
ADD CONSTRAINT FK_CUNGCAP_LOAIDV
FOREIGN KEY (MALOAIDV) REFERENCES LOAIDICHVU(MALOAIDV);

ALTER TABLE CUNGCAP
ADD CONSTRAINT FK_CUNGCAP_CHINHANH
FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN);

ALTER TABLE LAMVIEC
ADD CONSTRAINT FK_LAMVIEC_CHINHANH
FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN);

ALTER TABLE LAMVIEC
ADD CONSTRAINT FK_LAMVIEC_NHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE QUANLY
ADD CONSTRAINT FK_QUANLY_NHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE QUANLY
ADD CONSTRAINT FK_QUANLY_CHINHANH
FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN);

ALTER TABLE BACSI
ADD CONSTRAINT FK_BACSI_NHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
