USE master;
GO

IF EXISTS (SELECT 1 FROM SYS.databases WHERE name = 'PetcareX')
    DROP DATABASE PetcareX;
go

CREATE DATABASE PetcareX;
GO
USE PetcareX;
GO


--- PARTITION
ALTER DATABASE PetcareX
ADD FILEGROUP FG_2025

ALTER DATABASE PetcareX
ADD FILEGROUP FG_2024

ALTER DATABASE PetcareX
ADD FILEGROUP FG_2023

ALTER DATABASE PetcareX
ADD FILEGROUP FG_2022
GO


ALTER DATABASE PetcareX
ADD FILE(
	NAME = 'HoaDon_2025',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HoaDon_2025.mdf',
	SIZE = 10MB,
	FILEGROWTH = 10MB
) TO FILEGROUP FG_2025;

ALTER DATABASE PetcareX
ADD FILE(
	NAME = 'HoaDon_2024',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HoaDon_2024.mdf',
	SIZE = 10MB,
	FILEGROWTH = 10MB
) TO FILEGROUP FG_2024;

ALTER DATABASE PetcareX
ADD FILE(
	NAME = 'HoaDon_2023',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HoaDon_2023.mdf',
	SIZE = 10MB,
	FILEGROWTH = 10MB
) TO FILEGROUP FG_2023;

ALTER DATABASE PetcareX
ADD FILE(
	NAME = 'HoaDon_2022',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HoaDon_2022.mdf',
	SIZE = 10MB,
	FILEGROWTH = 10MB
) TO FILEGROUP FG_2022;
GO

CREATE PARTITION FUNCTION pf_HoaDonByNgayLap(DATETIME)
AS RANGE RIGHT 
FOR VALUES ('2023-01-01', '2024-01-01', '2025-01-01') 
GO

CREATE PARTITION SCHEME ps_HoaDonByNgayLap
AS PARTITION pf_HoaDonByNgayLap
TO (FG_2022, FG_2023, FG_2024, FG_2025);
GO
--- KHACH HANG VA THU CUNG

--- KHAM BENH VA TIEM PHONG

--- KINH DOANH
CREATE TABLE HOADON (
    MAHD CHAR(5) PRIMARY KEY,
    NGAYLAP DATETIME CHECK (NGAYLAP <= GETDATE()),
    KHUYENMAI INTEGER CHECK (KHUYENMAI >= 0),
    TONGTIEN DECIMAL(12, 2) CHECK (TONGTIEN > 0),
    DIEM INTEGER,
    MACN CHAR(5) NOT NULL,
    MAKH CHAR(10) NOT NULL,
    MANV CHAR(5) NOT NULL
)

CREATE TABLE HOADON_partitioned (
    MAHD CHAR(5) NOT NULL,
    NGAYLAP DATETIME CHECK (NGAYLAP <= GETDATE()),
    KHUYENMAI INTEGER CHECK (KHUYENMAI >= 0),
    TONGTIEN DECIMAL(12, 2) CHECK (TONGTIEN > 0),
    DIEM INTEGER,
    MACN CHAR(5) NOT NULL,
    MAKH CHAR(10) NOT NULL,
    MANV CHAR(5) NOT NULL
    CONSTRAINT PK_HOADON_partitioned PRIMARY KEY CLUSTERED (NGAYLAP, MAHD) ON ps_HoaDonByNgayLap(NGAYLAP)
)

CREATE TABLE SanPham (
    MASP CHAR(5) PRIMARY KEY,
    TENSP NVARCHAR(50) NOT NULL,
    DONGIA DECIMAL(12, 2) NOT NULL CHECK (DONGIA > 0),
    TONKHO INTEGER NOT NULL,
    LOAI NVARCHAR(10) NOT NULL CHECK (LOAI IN (N'Sản phẩm', N'Thuốc', N'Vacxin', N'Gói tiêm', N'Dịch vụ'))
)

CREATE TABLE ChiTietHoaDon(
    MAHD CHAR(5),
    MASP CHAR(5),
    SOLUONG INTEGER CHECK (SOLUONG > 0)
    CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (MAHD, MASP)
)

CREATE TABLE DichVu (
    MADV CHAR(5) PRIMARY KEY,
    MALOAIDV CHAR(5) NOT NULL,
    THOIGIANDUKIEN INTEGER CHECK (THOIGIANDUKIEN > 0)
)

CREATE TABLE Thuoc (
    MATHUOC CHAR(5) PRIMARY KEY,
    DONVI NVARCHAR(5) NOT NULL,
    NGAYSX DATE NOT NULL CHECK (NGAYSX <= GETDATE()),
    HSD INTEGER NOT NULL CHECK (HSD > 0)
)

CREATE TABLE VACXIN (
    MAVACXIN CHAR(5) PRIMARY KEY,
    NGAYSX DATE NOT NULL CHECK (NGAYSX <= GETDATE()),
    DOTUOIAPDUNG INTEGER NOT NULL CHECK (DOTUOIAPDUNG > 0),
    LIEULUONG INTEGER CHECK (LIEULUONG > 0)
)

CREATE TABLE GoiTiem (
    MAGOITIEM CHAR(5) PRIMARY KEY,
    THOIGIAN INTEGER NOT NULL CHECK (THOIGIAN >= 0),
    KHUYENMAI INTEGER NOT NULL CHECK (KHUYENMAI >= 0)
)

CREATE TABLE ChiTietGoiTiem (
    MAGOITIEM CHAR(5),
    MAVACXIN CHAR(5),
    SOLUONG INTEGER CHECK (SOLUONG > 0)
    CONSTRAINT PK_CHITIETGOITIEM PRIMARY KEY (MAGOITIEM, MAVACXIN)
)

CREATE TABLE DangKyGoiTiem (
    MAGOITIEM CHAR(5),
    MATC CHAR(5)
    CONSTRAINT PK_DANGKYGOITIEM PRIMARY KEY (MAGOITIEM, MATC)
)
GO

--- CHI NHANH VA NHAN SU

------
-- KHOA NGOAI
------

/*
ALTER TABLE HOADON
ADD 
    CONSTRAINT FK_HOADON_CHINHANH FOREIGN KEY (MACN) REFERENCES ChiNhanh(MACN),
    CONSTRAINT FK_HOADON_KHACHANG FOREIGN KEY (MAKH) REFERENCES KhachHang(MAKH),
    CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV) REFERENCES NhanVien(MANV)

ALTER TABLE HOADON_partitioned
ADD 
    CONSTRAINT FK_HOADON_Paritioned_CHINHANH FOREIGN KEY (MACN) REFERENCES ChiNhanh(MACN),
    CONSTRAINT FK_HOADON_Paritioned_KHACHANG FOREIGN KEY (MAKH) REFERENCES KhachHang(MAKH),
    CONSTRAINT FK_HOADON_Paritioned_NHANVIEN FOREIGN KEY (MANV) REFERENCES NhanVien(MANV)

ALTER TABLE ChiTietHoaDon
ADD 
    CONSTRAINT FK_CHITIETHOADON_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_CHITIETHOADON_HOADON_Paritioned FOREIGN KEY (MAHD) REFERENCES HOADON_partitioned(MAHD),
    CONSTRAINT FK_CHITIETHOADON_SANPHAM FOREIGN KEY (MASP) REFERENCES SanPham(MASP)

ALTER TABLE DichVu
ADD 
    CONSTRAINT FK_DICHVU_SANPHAM FOREIGN KEY (MADV) REFERENCES SanPham(MASP),
    CONSTRAINT FK_DICHVU_LOAI FOREIGN KEY (MALOAIDV) REFERENCES LoaiDichVu(MALOAIDV)

ALTER TABLE Thuoc
ADD CONSTRAINT FK_THUOC_SANPHAM FOREIGN KEY (MATHUOC) REFERENCES SanPham(MASP)

ALTER TABLE VACXIN
ADD CONSTRAINT FK_VACXIN_SANPHAM FOREIGN KEY (MAVACXIN) REFERENCES SanPham(MASP)

ALTER TABLE GoiTiem
ADD CONSTRAINT FK_GOITIEM_SANPHAM FOREIGN KEY (MAGOITIEM) REFERENCES SanPham(MASP)

ALTER TABLE ChiTietGoiTiem
ADD 
    CONSTRAINT FK_CHITIETGOITIEM_GOITIEM FOREIGN KEY (MAGOITIEM) REFERENCES GoiTiem(MAGOITIEM),
    CONSTRAINT FK_CHITIETGOITIEM_VACXIN FOREIGN KEY (MAVACXIN) REFERENCES Vacxin(MAVACXIN)

ALTER TABLE DangKyGoiTiem
ADD 
    CONSTRAINT FK_DANGKYGOITIEM_GOITIEM FOREIGN KEY (MAGOITIEM) REFERENCES GoiTiem(MAGOITIEM),
    CONSTRAINT FK_DANGKYGOITIEM_THUCUNG FOREIGN KEY (MATC) REFERENCES ThuCung(MATC)
GO
*/

