USE master;
GO

IF EXISTS (SELECT 1 FROM SYS.databases WHERE name = 'PetcareX')
    DROP DATABASE PetcareX;
go

CREATE DATABASE PetcareX;
GO
USE PetcareX;
GO

-- PARTITION
ALTER DATABASE PetcareX
ADD FILEGROUP FG_2022;
GO

ALTER DATABASE PetcareX
ADD FILEGROUP FG_2023;
GO

ALTER DATABASE PetcareX
ADD FILEGROUP FG_2024;
GO

ALTER DATABASE PetcareX
ADD FILEGROUP FG_2025;
GO

ALTER DATABASE PetcareX
ADD FILE(
    NAME = 'LichHen_2022',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\LichHen_2022.mdf',
    SIZE = 10MB,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_2022;
GO

ALTER DATABASE PetcareX
ADD FILE(
    NAME = 'LichHen_2023',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\LichHen_2023.mdf',
    SIZE = 10MB,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_2023;
GO

ALTER DATABASE PetcareX
ADD FILE(
    NAME = 'LichHen_2024',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\LichHen_2024.mdf',
    SIZE = 10MB,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_2024;
GO

ALTER DATABASE PetcareX
ADD FILE(
    NAME = 'LichHen_2025',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\LichHen_2025.mdf',
    SIZE = 10MB,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_2025;
GO

-- PARTITION FUNCTION
CREATE PARTITION FUNCTION pf_LichHenByNgayHen (DATE)
AS RANGE RIGHT
FOR VALUES ('2023-01-01', '2024-01-01', '2025-01-01');
GO

CREATE PARTITION SCHEME ps_LichHenByNgayHen
AS PARTITION pf_LichHenByNgayHen
TO (FG_2022, FG_2023, FG_2024, FG_2025);
GO
--- KHACH HANG VA THU CUNG
CREATE TABLE CAPBAC (
    MACAPBAC CHAR(5) PRIMARY KEY,
    TENCAPBAC NVARCHAR(15) NOT NULL CHECK (TENCAPBAC IN (N'Đồng', N'Bạc', N'Vàng', N'Bạch Kim', N'Kim Cương')),
    MUCCHITIEU DECIMAL(18,2) NOT NULL CHECK (MUCCHITIEU >= 0)
);

CREATE TABLE KHACHHANG (
    MAKH CHAR(5) PRIMARY KEY,
    TENKH NVARCHAR(100) NOT NULL,  
    SDT CHAR(10) NOT NULL, 
    DIACHI NVARCHAR(200) NULL,
    MACAPBAC CHAR(5) NULL,
    -- SDT phải là duy nhất
    CONSTRAINT UQ_KHACHHANG_SDT UNIQUE (SDT)
);


CREATE TABLE THUCUNG (
    MATC CHAR(5) PRIMARY KEY,
    LOAI NVARCHAR(30) NOT NULL,
    GIONG NVARCHAR(50) NULL,
    TUOI TINYINT NULL,
    GIOITINH NVARCHAR(5) NOT NULL CHECK (GIOITINH IN (N'Đực', N'Cái')),
    TINHTRANG NVARCHAR(20) NOT NULL CHECK (TINHTRANG IN (N'Bình thường', N'Đang điều trị')),
    MAKH CHAR(5) NOT NULL
);


CREATE TABLE LICHHEN (
    MALICHHEN CHAR(5) PRIMARY KEY,
    NGAYHEN DATE NOT NULL,
    THOIGIAN TIME NOT NULL,
    NOIDUNG NVARCHAR(200) NULL,
    MAKH CHAR(5) NOT NULL,
    MACN CHAR(5) NOT NULL,    
    MALOAIDV INT NOT NULL,    
    CONSTRAINT UQ_LICHEN_NGAYHEN_THOIGIAN_MACN_MAKH
        UNIQUE (NGAYHEN, THOIGIAN, MACN, MAKH)
);

CREATE TABLE LICHHEN_partitioned (
    MALICHHEN CHAR(5) NOT NULL PRIMARY KEY,
    NGAYHEN   DATE          NOT NULL,
    THOIGIAN  TIME          NOT NULL,
    NOIDUNG   NVARCHAR(200) NULL,
    MAKH      CHAR(5)       NOT NULL,
    MACN      CHAR(5)       NOT NULL,
    MALOAIDV  INT           NOT NULL,

    CONSTRAINT PK_LICHEN_partitioned
        PRIMARY KEY CLUSTERED (NGAYHEN, MaLichHen)
        ON ps_LichHenByNgayHen(NGAYHEN),
    CONSTRAINT UQ_LICHEN_partitioned_NgayHen_ThoiGian_MaCN_MaKH
        UNIQUE (NGAYHEN, THOIGIAN, MACN, MAKH)
        ON ps_LichHenByNgayHen(NGAYHEN)
);

CREATE TABLE CHITIEU (
    MAKH CHAR(5) NOT NULL PRIMARY KEY,
    NAM SMALLINT NOT NULL,
    THANG TINYINT NOT NULL CHECK (THANG BETWEEN 1 AND 12),
    CHITIEU DECIMAL(12,2) NOT NULL CHECK (CHITIEU >= 0),
    CONSTRAINT PK_CHITIEU PRIMARY KEY (MAKH, NAM, THANG),
);

CREATE TABLE DANHGIA (
    MADANHGIA CHAR(5) PRIMARY KEY,
    DIEMDICHVU TINYINT NOT NULL CHECK (DIEMDICHVU BETWEEN 1 AND 5),
    THAIDONHANVIEN TINYINT NOT NULL CHECK (THAIDONHANVIEN BETWEEN 1 AND 5),
    MUCDO HAILONG TINYINT NOT NULL CHECK (MUCDO HAILONG BETWEEN 1 AND 5),
    BINHLUAN NVARCHAR(500) NULL,
    MAKH CHAR(5) NOT NULL,
    MAHD CHAR(5) NOT NULL,
    -- Một hóa đơn chỉ được đánh giá một lần
    CONSTRAINT UQ_DANHGIA_MAHD UNIQUE (MAHD)
);
GO



--- KHAM BENH VA TIEM PHONG

--- KINH DOANH

--- CHI NHANH VA NHAN SU

------
-- KHOA NGOAI
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_CAPBAC
    FOREIGN KEY (MACAPBAC) REFERENCES CAPBAC(MACAPBAC);

ALTER TABLE THUCUNG
ADD CONSTRAINT FK_THUCUNG_KHACHHANG
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

ALTER TABLE CHITIEU
ADD CONSTRAINT FK_CHITIEU_KHACHHANG
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

ALTER TABLE LICHHEN
ADD CONSTRAINT FK_LICHEN_KHACHHANG
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);
    
ALTER TABLE LICHHEN
ADD CONSTRAINT FK_LICHEN_CHINHANH
    FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN);

ALTER TABLE LICHHEN
ADD CONSTRAINT FK_LICHEN_LOAIDICHVU
    FOREIGN KEY (MALOAIDV) REFERENCES LOAIDICHVU(MALOAIDV);

ALTER TABLE LICHHEN_partitioned
ADD CONSTRAINT FK_LICHEN_partitioned_KHACHHANG
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

ALTER TABLE LICHHEN_partitioned
ADD CONSTRAINT FK_LICHEN_partitioned_CHINHANH
    FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN);

ALTER TABLE LICHHEN_partitioned
ADD CONSTRAINT FK_LICHEN_partitioned_LOAIDICHVU
    FOREIGN KEY (MALOAIDV) REFERENCES LOAIDICHVU(MALOAIDV);

ALTER TABLE DANHGIA
ADD CONSTRAINT FK_DANHGIA_KHACHHANG
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

ALTER TABLE DANHGIA
ADD CONSTRAINT FK_DANHGIA_HOADON
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);
------

