-- script for fix data
USE PetcareX;
GO


UPDATE HOADON
SET TongTien = 
    ISNULL(
        (SELECT SUM(CTHD.SOLUONG * CTHD.GIABAN)
            FROM ChiTietHoaDon CTHD
            WHERE CTHD.MAHD = HOADON.MAHD), 0)

UPDATE CHITIEU
SET CHITIEU = 
    ISNULL(
        (
            SELECT SUM(HD.TONGTIEN * HD.KHUYENMAI / 100.0)
            FROM HOADON HD
            WHERE YEAR(HD.NGAYLAP) = CHITIEU.NAM
            ), 0    
        )

UPDATE SANPHAM
SET LOAI = N'Dịch vụ'
WHERE EXISTS (
    SELECT 1 
    FROM DICHVU DV
    WHERE DV.MADV = SANPHAM.MASP
)

UPDATE SANPHAM
SET LOAI = N'Vacxin'
WHERE EXISTS (
    SELECT 1 
    FROM VACXIN VX
    WHERE VX.MAVACXIN = SANPHAM.MASP
)

UPDATE SANPHAM
SET LOAI = N'Thuốc'
WHERE EXISTS (
    SELECT 1 
    FROM THUOC TH
    WHERE TH.MATHUOC = SANPHAM.MASP
)

UPDATE SANPHAM
SET LOAI = N'Gói tiêm'
WHERE EXISTS (
    SELECT 1 
    FROM GoiTiem GT
    WHERE GT.MAGOITIEM  = SANPHAM.MASP
)

UPDATE NHANVIEN
SET VAITRO = 'NV'

UPDATE NHANVIEN
SET VAITRO = 'BS'
WHERE EXISTS (
    SELECT 1 
    FROM BACSI BS
    WHERE BS.MANV = NHANVIEN.MANV
)
UPDATE NHANVIEN
SET VAITRO = 'QL'
WHERE EXISTS (
    SELECT 1 
    FROM QUANLY QL
    WHERE QL.MANV = NHANVIEN.MANV
)

SELECT * FROM LAMVIEC

UPDATE LAMVIEC
SET VAITRO = 'BS'
WHERE EXISTS (
    SELECT 1 
    FROM BACSI BS
    WHERE BS.MANV = LAMVIEC.MANV
)

UPDATE LAMVIEC
SET VAITRO = 'QL'
WHERE EXISTS (
    SELECT 1 
    FROM QUANLY QL
    WHERE QL.MANV = LAMVIEC.MANV
)