    -- script for fix data
    USE PetcareX;
    GO

UPDATE HOADON
SET TONGTIEN = ISNULL((
    SELECT SUM(SOLUONG * GIABAN)
    FROM CHITIETHOADON ct
    WHERE HOADON.MAHD = ct.MAHD
), 0)


UPDATE HOADON
SET KHUYENMAI = 0
WHERE KHUYENMAI IS NULL

    UPDATE HOADON
    SET TongTien = 
        ISNULL(
            (SELECT SUM(CTHD.SOLUONG * CTHD.GIABAN)
                FROM ChiTietHoaDon CTHD
                WHERE CTHD.MAHD = HOADON.MAHD), 0)
    UPDATE CHITIEU
    SET CHITIEU = 
        ISNULL(
            (
                SELECT SUM(HD.TONGTIEN * HD.KHUYENMAI / 100.0)
                FROM HOADON HD
                WHERE YEAR(HD.NGAYLAP) = CHITIEU.NAM
                ), 0    
            )


UPDATE NHANVIEN
SET VAITRO = 'NV'
    UPDATE SANPHAM
    SET LOAI = N'Dịch vụ'
    WHERE EXISTS (
        SELECT 1 
        FROM DICHVU DV
        WHERE DV.MADV = SANPHAM.MASP
    )

    UPDATE SANPHAM
    SET LOAI = N'Vacxin'
    WHERE EXISTS (
        SELECT 1 
        FROM VACXIN VX
        WHERE VX.MAVACXIN = SANPHAM.MASP
    )

    UPDATE SANPHAM
    SET LOAI = N'Thuốc'
    WHERE EXISTS (
        SELECT 1 
        FROM THUOC TH
        WHERE TH.MATHUOC = SANPHAM.MASP
    )

    UPDATE SANPHAM
    SET LOAI = N'Gói tiêm'
    WHERE EXISTS (
        SELECT 1 
        FROM GoiTiem GT
        WHERE GT.MAGOITIEM  = SANPHAM.MASP
    )

    UPDATE NHANVIEN
    SET VAITRO = 'NV'
    UPDATE NHANVIEN
    SET VAITRO = 'BS'
    WHERE EXISTS (
        SELECT 1 
        FROM BACSI BS
        WHERE BS.MANV = NHANVIEN.MANV
    )
    UPDATE NHANVIEN
    SET VAITRO = 'QL'
    WHERE EXISTS (
        SELECT 1 
        FROM QUANLY QL
        WHERE QL.MANV = NHANVIEN.MANV
    )

UPDATE LAMVIEC
SET VAITRO = 'BS'
WHERE EXISTS (
    SELECT 1 
    FROM BACSI BS
    WHERE BS.MANV = LAMVIEC.MANV
)

UPDATE LAMVIEC
SET VAITRO = 'QL'
WHERE EXISTS (
    SELECT 1 
    FROM QUANLY QL
    WHERE QL.MANV = LAMVIEC.MANV
)

UPDATE CAPBAC
SET MUCCHITIEU = 0,
    MUCGIUHANG = 0
WHERE TENCAPBAC = N'Cơ bản'

UPDATE CAPBAC
SET MUCCHITIEU = 5000000,
    MUCGIUHANG = 3000000
WHERE TENCAPBAC = N'Thân thiết'

UPDATE CAPBAC
SET MUCCHITIEU = 12000000,
    MUCGIUHANG = 8000000
WHERE TENCAPBAC = N'VIP'

UPDATE KHACHHANG
SET DIEMTICHLUY = 0

UPDATE KHACHHANG
SET DIEMTICHLUY = ISNULL(
    (SELECT SUM(TONGTIEN * KHUYENMAI / 100.0) / 10000
    FROM HOADON HD
    WHERE HD.MAKH = KHACHHANG.MAKH)
    , 0)

UPDATE KHACHHANG 
SET TENCAPBAC = N'Cơ bản'
WHERE (SELECT SUM(CHITIEU) FROM CHITIEU WHERE CHITIEU.MAKH = KHACHHANG.MAKH GROUP BY Nam) < 5000000

UPDATE KHACHHANG 
SET TENCAPBAC = N'Thân thiết'
WHERE (SELECT SUM(CHITIEU) FROM CHITIEU WHERE CHITIEU.MAKH = KHACHHANG.MAKH GROUP BY Nam) >= 5000000
AND (SELECT SUM(CHITIEU) FROM CHITIEU WHERE CHITIEU.MAKH = KHACHHANG.MAKH GROUP BY Nam) < 12000000

UPDATE KHACHHANG 
SET TENCAPBAC = N'VIP'
WHERE (SELECT SUM(CHITIEU) FROM CHITIEU WHERE CHITIEU.MAKH = KHACHHANG.MAKH GROUP BY Nam) >= 12000000
    SELECT * FROM LAMVIEC

    UPDATE LAMVIEC
    SET VAITRO = 'BS'
    WHERE EXISTS (
        SELECT 1 
        FROM BACSI BS
        WHERE BS.MANV = LAMVIEC.MANV
    )

    UPDATE LAMVIEC
    SET VAITRO = 'QL'
    WHERE EXISTS (
        SELECT 1 
        FROM QUANLY QL
        WHERE QL.MANV = LAMVIEC.MANV
    )

