USE PetcareX;
GO
IF OBJECT_ID('dbo.TAIKHOAN', 'U') IS NOT NULL DROP TABLE dbo.TAIKHOAN;
GO

CREATE TABLE TAIKHOAN (
    TENDANGNHAP VARCHAR(20) PRIMARY KEY, 
    MATKHAU     CHAR(32) NOT NULL,       
    SALT        VARCHAR(36) NOT NULL,    
    TRANGTHAI   BIT DEFAULT 1,           
    MANV        INTEGER NULL,
    MAKH        INTEGER NULL,
    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_TAIKHOAN_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT CHK_ValidOwner CHECK (
        (MANV IS NOT NULL AND MAKH IS NULL) OR 
        (MANV IS NULL AND MAKH IS NOT NULL)
    )
);
GO

DELETE FROM TAIKHOAN WHERE TENDANGNHAP IN ('taikhoanquanli', 'taikhoanbacsi', 'taikhoannhanvien', 'taikhoankhachhang');
DELETE FROM LAMVIEC WHERE MANV IN (1, 3, 5);

GO

DECLARE @PassHash CHAR(32) = 'fb276fb0ed6cdd1639bd678d3ace8614'; -- mật khẩu 123456
DECLARE @Salt CHAR(3) = 'ABC';

INSERT INTO TAIKHOAN (TENDANGNHAP, MATKHAU, SALT, TRANGTHAI, MANV, MAKH)
VALUES 
('taikhoanbacsi',    @PassHash, @Salt, 1, 1,    NULL), -- MANV 1
('taikhoanquanli',   @PassHash, @Salt, 1, 3,    NULL), -- MANV 3
('taikhoannhanvien', @PassHash, @Salt, 1, 5,    NULL), -- MANV 5
('taikhoankhachhang', @PassHash, @Salt, 1, NULL, 1);    -- MAKH 1
GO

INSERT INTO LAMVIEC (MACN, MANV, NGAYBATDAU, NGAYKETTHUC, VAITRO)
VALUES 
(1, 3, '2023-01-01', NULL, 'QL'), -- Khớp với taikhoanquanli
(1, 1, '2023-01-01', NULL, 'BS'), -- Khớp với taikhoanbacsi
(1, 5, '2023-01-01', NULL, 'NV'); -- Khớp với taikhoannhanvien
GO

-- 5. KIỂM TRA LẠI SỰ ĐỒNG BỘ
PRINT '--- KIỂM TRA ĐỒNG BỘ ---';
SELECT 
    TK.TENDANGNHAP, 
    NV.HOTEN, 
    NV.VAITRO AS VAITRO_GOC, 
    LV.VAITRO AS VAITRO_LAMVIEC,
    LV.MACN
FROM TAIKHOAN TK
JOIN NHANVIEN NV ON TK.MANV = NV.MANV
JOIN LAMVIEC LV ON NV.MANV = LV.MANV
WHERE TK.TENDANGNHAP != 'taikhoankhachhang';

